networks:
  agent:
    name: agent

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - '8022:8022'
      - '3000:3000'
    restart: on-failure
    depends_on: backend
    networks: agent
    environment:
      - BACKEND_URL=${BACKEND_URL}
  backend:
    container_name: backend
    build: ./backend
    ports:
      - '9022:8022'
      - '8000:8000'
    restart: on-failure
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - OPENROUTER_API_URL=${OPENROUTER_API_URL}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    networks: agent
